package dev.noa.kakao;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/** Resolves KakaoTalk action targets from DEX and reflection signatures. */
public final class KakaoSignatureResolver {
    private static volatile State state;
    private KakaoSignatureResolver() {}

    /** Installs the source and call-graph index generated by the Rust runtime. */
    public static void installIndex(String encoded) throws Exception {
        KakaoSignatureIndex.Data index = KakaoSignatureIndex.decode(encoded);
        Object application = currentApplication();
        Class<?> context = Class.forName("android.content.Context");
        ClassLoader loader = (ClassLoader) context.getMethod("getClassLoader")
                .invoke(application);
        synchronized (KakaoSignatureResolver.class) {
            state = new State(loader, index.classesBySource, index.operations);
        }
    }

    /** Returns a room while discovering and caching the repository relationship. */
    public static Object findRoom(long roomId) throws Exception {
        return KakaoRoomResolver.find(roomId);
    }

    /** Performs an open-chat kick using only validated runtime relationships. */
    public static void kick(long roomId, long userId, long commandId) throws Exception {
        KakaoRoomResolver.kick(roomId, userId, commandId);
    }

    /** Dispatches KakaoTalk's open-chat message rewrite (hide) operation. */
    public static void hideMessage(long roomId, long logId, int logType,
            long commandId, String message) throws Exception {
        KakaoMessageResolver.hide(roomId, logId, logType, commandId, message);
    }

    /** Resolves an open-profile URL through cache and repository object signatures. */
    public static String openProfileUrl(long linkId) throws Exception {
        return KakaoOpenChatResolver.openProfileUrl(linkId);
    }

    /** Converts a connection response to the stable OpenLink model by type relationships. */
    public static Object convertOpenLink(Object response) throws Exception {
        return KakaoOpenChatResolver.convertOpenLink(response);
    }

    /** Finds a room belonging to an open-link ID across renamed repository methods. */
    public static Object findOpenChatRoom(long linkId) throws Exception {
        return KakaoOpenChatResolver.findRoom(linkId);
    }

    public static boolean hasLongIdentity(Object target, long value) {
        return target != null && KakaoReflection.hasLongValue(target, value);
    }

    public static boolean locoConnected() throws Exception {
        return KakaoLocoStateResolver.connected();
    }

    /** Resolves OpenLink.linkId by round-tripping candidate IDs through OlkManager. */
    public static Long openLinkId(Object openLink) throws Exception {
        return KakaoOpenChatResolver.linkId(openLink);
    }

    public static boolean isOpenProfile(Object openLink) throws Exception {
        return KakaoOpenChatResolver.isOpenProfile(openLink);
    }

    /** Dispatches resend with a listener proxy matching the current KakaoTalk ABI. */
    public static void resend(Object room, Object entry, long commandId) throws Exception {
        KakaoSendingResolver.resend(room, entry, commandId);
    }

    /** Diagnostic text used by startup logs and compatibility reports. */
    public static String describe() throws Exception {
        State value = appState();
        int candidates = 0;
        for (List<String> names : value.classesBySource.values()) {
            candidates += names.size();
        }
        return "rust-index, source-signatures=" + value.classesBySource.size()
                + ", candidates=" + candidates;
    }

    /**
     * Resolves every startup-safe semantic binding without invoking a KakaoTalk action.
     * This is intentionally driven only by DEX source and call-graph signatures.
     */
    public static String verifySignatures() throws Exception {
        String[] roles = {
            "room-manager",
            "room-api",
            "member-repository",
            "open-link-manager",
            "open-profile-repository",
            "open-link-connection",
            "open-link",
            "open-chat-kakao-profile",
            "open-chat-open-profile",
            "open-chat-profile-use-type",
            "sending-log-manager",
            "sending-log-request",
            "sending-log-mode",
        };
        List<String> resolved = new ArrayList<>();
        for (String role : roles) {
            resolved.add(role + "=" + classFor(role).getName());
        }
        resolved.add(KakaoOperationResolver.verify("chat-on-room", "room-api"));
        resolved.add(KakaoOperationResolver.verify("join-link", "room-api"));
        resolved.add(KakaoOperationResolver.verify("prepare-resend", "sending-log-manager"));
        resolved.add("loco-state=" + KakaoLocoStateResolver.describe());
        return String.join(", ", resolved);
    }

    /** Returns classes compiled from a source file, as recorded in the APK DEX. */
    public static String[] sourceClassNames(String source) throws Exception {
        List<String> names = appState().classesBySource.get(source);
        if (names == null || names.isEmpty()) {
            throw new ClassNotFoundException("DEX source signature was not found: " + source);
        }
        return names.toArray(new String[0]);
    }

    /** Resolves a semantic class role without relying on an obfuscated class name. */
    public static Class<?> classFor(String role) throws Exception {
        return KakaoClassResolver.classFor(role);
    }

    /** Returns the singleton or Kotlin companion associated with a semantic role. */
    public static Object objectFor(String role) throws Exception {
        return KakaoClassResolver.objectFor(role);
    }

    /** Returns a static value by its stable Java supertype instead of a field name. */
    public static Object staticValueFor(String role, String typeName) throws Exception {
        return KakaoClassResolver.staticValueFor(role, typeName);
    }

    /** Invokes a method selected by a protocol/call-graph signature. */
    public static Object invokeOperation(String operation, Object target, Object[] arguments)
            throws Exception {
        return KakaoOperationResolver.invoke(operation, target, arguments);
    }

    static List<Class<?>> sourceClasses(String source) throws Exception {
        State value = appState();
        List<String> names = value.classesBySource.get(source);
        if (names == null || names.isEmpty()) {
            throw new ClassNotFoundException("DEX source signature was not found: " + source);
        }
        List<Class<?>> classes = new ArrayList<>();
        for (String name : names) {
            try {
                classes.add(Class.forName(name, false, value.loader));
            } catch (Throwable ignored) {
            }
        }
        return classes;
    }

    static ClassLoader appLoader() throws Exception {
        return appState().loader;
    }

    static List<KakaoSignatureIndex.MethodRef> operationRefs(String operation) throws Exception {
        return appState().operations.get(operation);
    }

    private static State appState() throws Exception {
        State cached = state;
        if (cached == null) {
            throw new IllegalStateException("Rust DEX signature index is not installed");
        }
        return cached;
    }

    private static Object currentApplication() throws Exception {
        Class<?> activityThread = Class.forName("android.app.ActivityThread");
        Object application = activityThread.getMethod("currentApplication").invoke(null);
        if (application == null) {
            throw new IllegalStateException("Android application is not ready");
        }
        return application;
    }

    private static final class State {
        final ClassLoader loader;
        final Map<String, List<String>> classesBySource;
        final Map<String, List<KakaoSignatureIndex.MethodRef>> operations;

        State(
                ClassLoader loader,
                Map<String, List<String>> classesBySource,
                Map<String, List<KakaoSignatureIndex.MethodRef>> operations) {
            this.loader = loader;
            this.classesBySource = classesBySource;
            this.operations = operations;
        }
    }

}
